<a href="https://colab.research.google.com/github/prajwal072/Python-basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [5]:
# 1-D Array
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)
arr1.reshape(1,6)

[1 2 3 4 5 6]
(6,)


array([[1, 2, 3, 4, 5, 6]])

In [6]:
# 2-D array
import numpy as np
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [7]:
np.arange(0,10,2)


array([0, 2, 4, 6, 8])

In [11]:
np.ones((3,4))
np.eye(1)

array([[1.]])

In [13]:
# Functions
arr1=np.array([1,2,3,4,5,6])
print(arr1.size)
print(arr1.dtype)
print(arr1.ndim)

6
int64
1


In [16]:
#vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1 2 3 4 5]


In [17]:
#Universal Functions
arr=np.array([1,2,3,4,5,6,7])
print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.sin(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]
[   2.71828183    7.3890561    20.08553692   54.59815003  148.4131591
  403.42879349 1096.63315843]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866 ]


In [18]:
#Mean Median
data=np.array([1,2,3,4,5])
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

3.0
3.0
1.4142135623730951
2.0


In [22]:
#Indexing and Slicing
arr3=np.array([[1,2,3,4],[7,8,9,10]])
print(arr3[0:2][0:2])

[[ 1  2  3  4]
 [ 7  8  9 10]]
